# Generated by Django 2.2.4 on 2022-02-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=90)),
                ('category', models.CharField(max_length=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_job', to='log_reg.Company')),
                ('user_job', models.ManyToManyField(related_name='jobs', to='log_reg.User')),
            ],
        ),
    ]
