# Generated by Django 2.2.4 on 2022-02-27 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
        ('jobpal_app', '0002_auto_20220227_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accept_reject', to='log_reg.Company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=95),
        ),
    ]
